name: CD with Pulumi

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure-1:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the latest Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Generate static website assets
      - name: Generate static website assets
        run: | 
          cd frontend
          npm install
          npm run build

      # Install dependencies
      - name: Install dependencies
        run: cd frontend && npm install

      # Prepare static assets
      - name: Prepare static assets
        run: cp -r frontend/out infrastructure-1

      # Configure AWS Credentials 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy infra with Pulumi
      - name: Deploy infra with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dev-mood-1
          work-dir: infrastructure-1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deploy-infrastructure-2:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the latest Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Generate static website assets
      - name: Generate static website assets
        run: | 
          cd frontend
          npm install
          npm run build

      # Install dependencies
      - name: Install dependencies
        run: cd frontend && npm install

      # Prepare static assets
      - name: Prepare static assets
        run: cp -r frontend/out infrastructure-2

      # Configure AWS Credentials 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy infra with Pulumi
      - name: Deploy infra with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dev-mood-2
          work-dir: infrastructure-2
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}